version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dm-manager
    # volumes:
    #   - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5423:5432"
  web:
    image: dm-manager
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/dm-manager?schema=public
    ports:
      - "5656:5656"
    depends_on:
      db:
        condition: service_started
